/*
 * AUTOGENERATED FILE
 * DO NOT MODIFY MANUALLY!!!
 */
extern "C" {
const char DESCRIPTION[255] __attribute__((section(".metadata_pool"))) =
    "****************" // placeholder for beggining
    "20260604T194628"  // DateTime using ISO-8601 format
    " "                // alignment
    "6b7396b8"         // STLIB commit
    "--------"         // ADJ commit
    "55069399"         // Board commit
    // the '=' is used for unparsing
    ;
}
