#pragma once
#include "ST-LIB.hpp"

/*Data packets for BCU
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    enum class Motor_State : uint8_t
    {
        INACTIVE = 0,
        ACTIVE = 1,
    };
    enum class Bcu_general_state : uint8_t
    {
        Connecting = 0,
        Operational = 1,
        Fault = 2,
    };
    enum class Bcu_operational_state : uint8_t
    {
        Idle = 0,
        Test_PWM = 1,
        Space_Vector = 2,
        Current_Control = 3,
        Speed_Control = 4,
    };
    enum class direction_speetec : uint8_t
    {
        BACKWARD = 0,
        FORWARD = 1,
    };
    

    static void Motor_Info_init(float &duty_cycle_u, float &duty_cycle_v, float &duty_cycle_w, uint32_t &commutation_frequency_hz, int64_t &dead_time_ns, Motor_State &Motor_State)
    {
        Motor_Info_packet = new HeapPacket(static_cast<uint16_t>(1700), &duty_cycle_u, &duty_cycle_v, &duty_cycle_w, &commutation_frequency_hz, &dead_time_ns, &Motor_State);
    }

    static void State_init(Bcu_general_state &Bcu_general_state, Bcu_operational_state &Bcu_operational_state)
    {
        State_packet = new HeapPacket(static_cast<uint16_t>(1701), &Bcu_general_state, &Bcu_operational_state);
    }

    static void Space_Vector_init(uint32_t &modulation_frequency_hz, float &modulation_index)
    {
        Space_Vector_packet = new HeapPacket(static_cast<uint16_t>(1702), &modulation_frequency_hz, &modulation_index);
    }

    static void DC_Link_init(float &dc_link_a_voltage, float &dc_link_b_voltage)
    {
        DC_Link_packet = new HeapPacket(static_cast<uint16_t>(1703), &dc_link_a_voltage, &dc_link_b_voltage);
    }

    static void Motor_Currents_init(float &current_u_inverter_a, float &current_v_inverter_a, float &current_w_inverter_a, float &current_u_inverter_b, float &current_v_inverter_b, float &current_w_inverter_b)
    {
        Motor_Currents_packet = new HeapPacket(static_cast<uint16_t>(1704), &current_u_inverter_a, &current_v_inverter_a, &current_w_inverter_a, &current_u_inverter_b, &current_v_inverter_b, &current_w_inverter_b);
    }

    static void SPEETEC_1_init(double &position_speetec, direction_speetec &direction_speetec, double &speed_speetec, double &acceleration_speetec)
    {
        SPEETEC_1_packet = new HeapPacket(static_cast<uint16_t>(1705), &position_speetec, &direction_speetec, &speed_speetec, &acceleration_speetec);
    }

    static void SPEETEC_2_init(double &position_speetec, direction_speetec &direction_speetec, double &speed_speetec, double &acceleration_speetec)
    {
        SPEETEC_2_packet = new HeapPacket(static_cast<uint16_t>(1706), &position_speetec, &direction_speetec, &speed_speetec, &acceleration_speetec);
    }

    static void Current_Control_init(float &d_current_reference, float &measured_d_current, float &d_current_error, float &q_current_reference, float &measured_q_current, float &q_current_error, float &electrical_angle, float &pi_id_output, float &pi_iq_output, float &angle_offset, float &target_u_voltage, float &target_v_voltage, float &target_w_voltage)
    {
        Current_Control_packet = new HeapPacket(static_cast<uint16_t>(1707), &d_current_reference, &measured_d_current, &d_current_error, &q_current_reference, &measured_q_current, &q_current_error, &electrical_angle, &pi_id_output, &pi_iq_output, &angle_offset, &target_u_voltage, &target_v_voltage, &target_w_voltage);
    }

    static void Speed_Control_init(float &target_linear_speed, float &output_iq_ref, float &linear_speed_error)
    {
        Speed_Control_packet = new HeapPacket(static_cast<uint16_t>(1708), &target_linear_speed, &output_iq_ref, &linear_speed_error);
    }

    public:
    inline static HeapPacket *Motor_Info_packet{nullptr};
    inline static HeapPacket *State_packet{nullptr};
    inline static HeapPacket *Space_Vector_packet{nullptr};
    inline static HeapPacket *DC_Link_packet{nullptr};
    inline static HeapPacket *Motor_Currents_packet{nullptr};
    inline static HeapPacket *SPEETEC_1_packet{nullptr};
    inline static HeapPacket *SPEETEC_2_packet{nullptr};
    inline static HeapPacket *Current_Control_packet{nullptr};
    inline static HeapPacket *Speed_Control_packet{nullptr};

#define COUNT_PACKETS 9

    inline static HeapPacket *packets[COUNT_PACKETS]{nullptr};
    inline static uint16_t packet_idx{0};

    inline static DatagramSocket *control_station_udp{nullptr};
    

    static void start()
    {
        if (Motor_Info_packet == nullptr) {
            ErrorHandler("Packet Motor_Info not initialized");
        }
        if (State_packet == nullptr) {
            ErrorHandler("Packet State not initialized");
        }
        if (Space_Vector_packet == nullptr) {
            ErrorHandler("Packet Space_Vector not initialized");
        }
        if (DC_Link_packet == nullptr) {
            ErrorHandler("Packet DC_Link not initialized");
        }
        if (Motor_Currents_packet == nullptr) {
            ErrorHandler("Packet Motor_Currents not initialized");
        }
        if (SPEETEC_1_packet == nullptr) {
            ErrorHandler("Packet SPEETEC_1 not initialized");
        }
        if (SPEETEC_2_packet == nullptr) {
            ErrorHandler("Packet SPEETEC_2 not initialized");
        }
        if (Current_Control_packet == nullptr) {
            ErrorHandler("Packet Current_Control not initialized");
        }
        if (Speed_Control_packet == nullptr) {
            ErrorHandler("Packet Speed_Control not initialized");
        }

        DataPackets::packets[0] = Motor_Info_packet;
        DataPackets::packets[1] = State_packet;
        DataPackets::packets[2] = Space_Vector_packet;
        DataPackets::packets[3] = DC_Link_packet;
        DataPackets::packets[4] = Motor_Currents_packet;
        DataPackets::packets[5] = SPEETEC_1_packet;
        DataPackets::packets[6] = SPEETEC_2_packet;
        DataPackets::packets[7] = Current_Control_packet;
        DataPackets::packets[8] = Speed_Control_packet;

        control_station_udp = new DatagramSocket("192.168.2.17",50400,"192.168.0.9",50400);
        
        Scheduler::register_task(10000/COUNT_PACKETS, +[](){
            HeapPacket *pack = DataPackets::packets[packet_idx];
            packet_idx = (packet_idx + 1) % COUNT_PACKETS;
            DataPackets::control_station_udp->send_packet(*pack);
            });

    }



};