#pragma once
#include "ST-LIB.hpp"

/*Order packets for BCU
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool Stop_Control_flag{false};
    inline static bool Start_Test_PWM_flag{false};
    inline static bool Configure_Commutation_Parameters_flag{false};
    inline static bool Start_Space_Vector_flag{false};
    inline static bool Start_Current_Control_flag{false};
    inline static bool Start_Speed_Control_flag{false};
    inline static bool Change_angle_offset_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *Stop_Control_order{nullptr};
    inline static HeapOrder *Start_Test_PWM_order{nullptr};
    inline static HeapOrder *Configure_Commutation_Parameters_order{nullptr};
    inline static HeapOrder *Start_Space_Vector_order{nullptr};
    inline static HeapOrder *Start_Current_Control_order{nullptr};
    inline static HeapOrder *Start_Speed_Control_order{nullptr};
    inline static HeapOrder *Change_angle_offset_order{nullptr};
    

    static void Stop_Control_init()
    {
        Stop_Control_order = new HeapOrder(1799, &Stop_Control_cb);
    }
    static void Start_Test_PWM_init(uint32_t &commutation_frequency_hz, float &duty_cycle_u, float &duty_cycle_v, float &duty_cycle_w)
    {
        Start_Test_PWM_order = new HeapOrder(1798, &Start_Test_PWM_cb, &commutation_frequency_hz, &duty_cycle_u, &duty_cycle_v, &duty_cycle_w);
    }
    static void Configure_Commutation_Parameters_init(uint32_t &commutation_frequency_hz, int64_t &dead_time_ns)
    {
        Configure_Commutation_Parameters_order = new HeapOrder(1797, &Configure_Commutation_Parameters_cb, &commutation_frequency_hz, &dead_time_ns);
    }
    static void Start_Space_Vector_init(uint32_t &commutation_frequency_hz, uint32_t &modulation_frequency_hz, float &voltage_reference, float &voltage_max)
    {
        Start_Space_Vector_order = new HeapOrder(1796, &Start_Space_Vector_cb, &commutation_frequency_hz, &modulation_frequency_hz, &voltage_reference, &voltage_max);
    }
    static void Start_Current_Control_init(uint32_t &commutation_frequency_hz, float &d_current_reference, float &q_current_reference)
    {
        Start_Current_Control_order = new HeapOrder(1792, &Start_Current_Control_cb, &commutation_frequency_hz, &d_current_reference, &q_current_reference);
    }
    static void Start_Speed_Control_init(float &target_linear_speed)
    {
        Start_Speed_Control_order = new HeapOrder(1791, &Start_Speed_Control_cb, &target_linear_speed);
    }
    static void Change_angle_offset_init(float &angle_offset)
    {
        Change_angle_offset_order = new HeapOrder(1780, &Change_angle_offset_cb, &angle_offset);
    }
    

    
    inline static ServerSocket *control_station_tcp{nullptr};
    

    static void start()
    {
        if (Stop_Control_order == nullptr) {
            PANIC("Order Stop_Control not initialized");
        }
        if (Start_Test_PWM_order == nullptr) {
            PANIC("Order Start_Test_PWM not initialized");
        }
        if (Configure_Commutation_Parameters_order == nullptr) {
            PANIC("Order Configure_Commutation_Parameters not initialized");
        }
        if (Start_Space_Vector_order == nullptr) {
            PANIC("Order Start_Space_Vector not initialized");
        }
        if (Start_Current_Control_order == nullptr) {
            PANIC("Order Start_Current_Control not initialized");
        }
        if (Start_Speed_Control_order == nullptr) {
            PANIC("Order Start_Speed_control not initialized");
        }
        if (Change_angle_offset_order == nullptr) {
            PANIC("Order Change_angle_offset not initialized");
        }
        

        control_station_tcp = new ServerSocket("192.168.2.17",50500);
        
    }

private:
    static void Stop_Control_cb()
    {
        Stop_Control_flag = true;
    }
    static void Start_Test_PWM_cb()
    {
        Start_Test_PWM_flag = true;
    }
    static void Configure_Commutation_Parameters_cb()
    {
        Configure_Commutation_Parameters_flag = true;
    }
    static void Start_Space_Vector_cb()
    {
        Start_Space_Vector_flag = true;
    }
    static void Start_Current_Control_cb()
    {
        Start_Current_Control_flag = true;
    }
    static void Start_Speed_Control_cb()
    {
        Start_Speed_Control_flag = true;
    }
    static void Change_angle_offset_cb()
    {
        Change_angle_offset_flag = true;
    }
    
};